language: java
jdk: oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: BVTBrSxqAQ9+79KWu8DSwLvkjwn1oQLEi7Hb5iA80i2QRYilALvC3ppAe5ONi/uk/57Zbm7lsoLiE23XIG2kjk1S95QbQEa+K9tyU84zguIKLAn1pQn+LylPC+q/yG50gHuX4eQ2kk81tTkpz/0vXj+ySnsdxjXNvcn/mmYzmzmCSYQyibbkdGBnQqpXz7EiOiDprm14nXv4J0IxTOF4ZBQvrAkCtyp6lcigzy6zJlWUyfNln7C9iIQKd+2KfF0tRmNH2kzM7FmUqZYmfi/HmFEZB5LMjHtnxI0SVV2UAxj4h+cZpyERVBWl35EQvQ+g5o2DttT9kSJV8b9x+EtnTGJ0BMUGzrfGj5k59b0QQW7OwCjLLnRAtvWbsLv3mlvjak+BN79IQdQ3sQeVdB7uqrcfe/IyrY3K/Lpo4muFeup7e48rz7Jy8b4EmCu2u3iB2UWFw14lW149l5ksL7xdZ8lR6zBOOy1R54Rtxy+uUMOYLSwQ2PZLopWs5AYnEBix5RMiw0+F0Iif5eguZKdlCXL7cEBWDV8nwx1Tl6R/c+gf+28ill2gMUK/oXZ/jhkQs0TSovpwczMu0v38okjh75B5EIc5yrv/mA3G+Bv2fzmUyuLDagDKgCS8K/Id1Dn20v1Vfs9r9WxRfsgeC6Ru3+mznsqO/vG1BjSShFAkdy8=
  app: serviciowebapi
