language: java
jdk: oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: +pNSOfACc5FSAre4zzLiqnr4EBJa5S/7fPXJ6hAb2NhegY5uZFAX7lcjHCeipBxLRpB4pMwaJyIFZAlW5yeOJtczxiL/fHeXWlp457uUOVeopLLmvaFFoI5JErjW3lDbZgXO73pY=
  app: apiservicioweb
